<header>
	<h1>Twitter #digiyards</h1>
</header>
<form action="" id="search-form">
	<fieldset>
		<input type="search" name="q" value="<?= $this->q ?>" placeholder="search" />
	</fieldset>
</form>
<div class="tweets">
	<?php foreach($this->tweets as $Tweet) { ?>
	<blockquote class="twitter-tweet">
		<p>
			<?= $this->escape($Tweet->text); ?>
		</p>&mdash; <?= $Tweet->getFromUserName(); ?> (@<?= $Tweet->getFromUser() ?>)
		<a href="https://twitter.com/twitterapi/status/<?= $Tweet->getId(); ?>" data-datetime="<?= $Tweet->getCreatedAtDate()->format('c') ?>">
			<?= $Tweet->getCreatedAtDate()->format('d.m.Y H:m') ?>
		</a>
	</blockquote>
	<?php } ?>
</div>