<!doctype html>
<html lang="de">
<head>
	<meta charset="utf-8">
	<title>Twitter-Wall</title>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<link rel="stylesheet" href="<?= $this->baseUrl; ?>css/screen.css">
	<link rel="author" href="<?= $this->baseUrl; ?>humans.txt" />
	<script src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
</head>
<body>
	<div role="main" id="main">
		<?= $this->layout()->content ?>
	</div>
</body>
</html>