<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="de-DE">
<head profile="http://gmpg.org/xfn/11">
	<!--[if IE 8]><meta http-equiv="X-UA-Compatible" content="IE=7" /><![endif]-->
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="google-site-verification" content="TZp-wkEIHksgKrXE8i_AobZ0TGz_2yx1ViOOzOOE7TQ" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
	<meta http-equiv="imagetoolbar" content="no" />
	<meta name="generator" content="WordPress 3.3.1" />
	<base href="http://berlinergazette.de" />
	<title>Twitter Wall</title>
</head>

<body class="archive category category-was-bleibt category-339 de_DE">
	<div id="app">
		<div id="header">
			<h1>
				<a href="http://berlinergazette.de" title="zur Startseite" rel="index">
					<img src="http://berlinergazette.de/wp-content/themes/bg/images/berliner_gazette_logo.gif" alt="" />
				</a>
			</h1>
		</div>
	</div>

	<?php echo $this->layout()->content ?>
</body>
</html>
